### ISSUE TITLE
CORS headers

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/lds-pdi#15]
For a smooth experience, it would be useful to add [CORS headers](http://tomcat.apache.org/tomcat-7.0-doc/config/filter.html#CORS_Filter) allowing requests from any domain. Maybe we'll restrict domains later on, but for the development period, it seems the easiest way.

**Comment by xristy** [comment]
Oooops! Wrong issue. The commit is for [owl-schema #62](https://github.com/BuddhistDigitalResourceCenter/owl-schema/issues/62)

**Comment by berger-n** [comment]
for now you get the following message in the resource selector of the BLMP :

`Error loading resource: Failed to fetch`

you need a plugin to bypass the issue when running locally

https://addons.mozilla.org/en-US/firefox/addon/cors-everywhere/ for Firefox

https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?utm_source=chrome-app-launcher-info-dialog for chrome

(make sure to switch this one off then on when launching Chrome - then switch it off because it will cause trouble on other sites eg youtube videos won't load)

**Comment by MarcAgate** [comment]
Cors support is now implemented through a Jersey ContainerResponseFilter in CorsFilter.java. To be tested in BLMP

**Comment by xristy** [comment]
I implemented the CORS fiter in the ldspdi/tomcat/conf/web.xml 2 days ago - see above. Was that de-implemented? I thought using a uniform approach in the various tomcats would effective from a maintenane perspective. I thought that was Élie's suggestion.

What is the reason for the Jersey approach?

**Comment by eroux** [comment]
I think it's because Nicolas [says](https://github.com/berger-n) it doesn't work
